"""Bundle DESIGN.md + the full source listing into one self-contained markdown file.

Motivation: the design document is meant to be handed to a reviewer (e.g. another
model) that has no access to this repository.  A single .md containing the design
plus every file that the design makes claims about is directly pasteable and cannot
go stale relative to the code (this script regenerates it from the real files).

Usage (from inside experiment/):
    python build_review_package.py            # writes REVIEW_PACKAGE.md
    python build_review_package.py --out X.md
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import List, Sequence

HERE = Path(__file__).resolve().parent
DESIGN = HERE / "DESIGN.md"

#: order matters: the reviewer reads the protocol before the implementation
CODE_FILES = [
    "cases.json",
    "common.py",
    "prompts.py",
    "config.py",
    "client.py",
    "parse.py",
    "run_experiment.py",
    "analyze.py",
    "inspect_prompts.py",
    "selfcheck.py",
    "verify_doc.py",
    ".env.example",
]

LANG = {
    ".py": "python",
    ".json": "json",
    ".example": "ini",
}


def language_of(path: Path) -> str:
    return LANG.get(path.suffix, "")


def demote_headings(markdown: str, levels: int = 2) -> str:
    """Shift markdown ATX headings down, skipping fenced code blocks.

    Part 1 is embedded under a `# Part 1` heading, so its own headings must move
    down to keep a sane outline.  Fenced blocks are skipped so that `# comment`
    lines inside code listings are never rewritten.
    """
    out: List[str] = []
    in_fence = False
    for line in markdown.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("```"):
            in_fence = not in_fence
            out.append(line)
            continue
        if not in_fence and line.startswith("#"):
            hashes = len(line) - len(line.lstrip("#"))
            if 1 <= hashes <= 6 and len(line) > hashes and line[hashes] == " ":
                line = "#" * min(6, hashes + levels) + line[hashes:]
        out.append(line)
    return "\n".join(out)


def build(out_path: Path) -> None:
    design_text = DESIGN.read_text(encoding="utf-8")
    parts: List[str] = []

    parts.append(
        "<!-- Generated by build_review_package.py. Do not edit by hand: edit DESIGN.md\n"
        "     and the source files, then regenerate. Every listing below is the literal\n"
        "     file content, so line numbers in the text match the code. -->\n"
    )
    parts.append(
        "# Review package — privileged future information and the LLM User Simulator\n\n"
        "This file has two parts:\n\n"
        "1. **Part 1 — Design document (v0.2).** The thing to review. Section 11 answers an "
        "earlier review of v0.1 point by point, including what I declined to change and why.\n"
        "2. **Part 2 — Complete source listing** of the artifact the design describes, so the "
        "review can check the document against the implementation without a repository.\n\n"
        "**How to review.** Part 1, Section 9 lists the specific questions I want challenged, "
        "ordered by how much damage a flaw would do to the conclusion. Section 8 lists the "
        "alternative explanations and the mitigation implemented for each. The most "
        "load-bearing claims to verify in Part 2 are:\n\n"
        "- `prompts.py` — is the prompt identical across conditions outside the "
        "`<information_access>` envelope, is `blind` really bare, and do "
        "`pretend_blind_conflict` / `pretend_blind_support` differ *only* in the requirement text?\n"
        "- `inspect_prompts.py` — does the audit actually check what Section 3.2 claims?\n"
        "- `run_experiment.py` — is the request schema frozen before the run, and are "
        "`ERROR`/`UNPARSED` samples preserved?\n"
        "- `common.py` — are the decision rates and the failure rates on the denominators "
        "Section 7 declares?\n\n"
        "**Status.** No real API call has been made yet; `results/` contains only the offline "
        "fake-client self-test.\n\n---\n\n"
    )

    # ---------------- Part 1 ------------------------------------------------
    parts.append("# Part 1 — Design document\n\n")
    parts.append(demote_headings(design_text).rstrip() + "\n\n---\n\n")

    # ---------------- Part 2 ------------------------------------------------
    parts.append("# Part 2 — Complete source listing\n\n")
    parts.append(
        "Every file below is included verbatim. Together they are the whole artifact: "
        "configuration, prompt construction, HTTP client, parser, runner, analysis, "
        "fairness audit, offline self-test and the doc-consistency checker. Runtime "
        "dependencies: Python standard library only, plus pandas in `analyze.py` "
        "(optional PyYAML only if the case file is YAML).\n\n"
    )

    for name in CODE_FILES:
        path = HERE / name
        body = path.read_text(encoding="utf-8").rstrip("\n")
        n_lines = body.count("\n") + 1
        n_chars = len(body)
        parts.append(f"## `experiment/{name}` — {n_lines} lines, {n_chars} chars\n\n")
        parts.append(f"```{language_of(path)}\n{body}\n```\n\n")

    parts.append(
        "## Files deliberately not included\n\n"
        "- `README.md` — the Chinese quick-start; its content is a subset of Part 1.\n"
        "- `results/_selftest_offline/*` — fake-client output from the offline test, "
        "explicitly not experimental data.\n"
        "- `results/<real run>/*` — does not exist yet (no API call has been made).\n"
    )

    out_path.write_text("".join(parts), encoding="utf-8")


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="bundle DESIGN.md + sources into one markdown file")
    parser.add_argument("--out", default=str(HERE / "REVIEW_PACKAGE.md"))
    args = parser.parse_args(argv)

    out_path = Path(args.out)
    build(out_path)
    text = out_path.read_text(encoding="utf-8")
    print(f"wrote {out_path}")
    print(f"  {len(text.splitlines())} lines, {len(text):,} chars (~{len(text) // 4:,} tokens)")
    for name in CODE_FILES:
        (HERE / name).read_text(encoding="utf-8")  # fail loudly if a listing source vanished
    print(f"  contains: DESIGN.md + {len(CODE_FILES)} source files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
